# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Duck Pond
taglines:
  - "A blog about making machines, programs, music, maths, physics... and ducks?"
  - "The blog needed a name"
  - "It looks like a blog, smells like a blog, pretty sure it's a blog"
  - "Quack quack!"
  - "The blog where ducks might be used, sometimes literally"
  - "* Disclaimer. This blog may or may not contain any actual duck"
  - "The place where I *duck* away from the world"
  - "The blog with a splendiferous name and a one-of-the-kind tagline"
email: "&#x65;&#x77;&#x6f;&#x6e;&#x35;&#x32;&#x31;&#x40;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;"
description: > # this means to ignore newlines until "baseurl:"
  A blog about making machines, programs, music, maths, physics... and ducks?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ernwong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ewon521
github_username: ErnWong

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
